name: Build and Test

on:
  pull_request:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: actions/checkout@v3
      - run: npm ci
